### ISSUE TITLE
How to require paloma properly in Rails 6 application

### ISSUE THREAD

**Issue by divyashivaram** [gnclmorais/paloma#10]
Hi, 
I'm planning to use Paloma to load specific javascript for my rails actions but confused about requiring the module. Since, Rails 6 does not have `app/assets/javascripts/application.js` file anymore, I'm not sure how/where should I add the line `//= require paloma`?

Thanks!!

**Comment by gnclmorais** [comment]
Hi @divyashivaram! Sorry for the late reply, I only noticed now…

I think a popular option for gem creators is to publish the JS part of a gem as an npm package, but to be honest, that’s not something I’m that interested in doing. The truth is that, if you’re using webpacker instead of sprockets, I don’t see a strong reason to use Paloma.

However, if you’re still interested in it, I cooked up a quick example. I created a [new branch](https://github.com/gnclmorais/paloma/tree/example-rails6) with a slimmed down Rails 6 app (with webpacker and without sprockets) where you can see a working example of importing the JavaScript files of the Paloma gem. If you enable ERB webpacker support, you can dynamically import the gem’s JavaScript files [like this](https://github.com/gnclmorais/paloma/blob/example-rails6/app/javascript/packs/application.js.erb#L12-L20). I hope it helps. 😃
